[package]
name = "migration"
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
sea-orm-migration = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-tokio-native-tls"] }
