[package]
name = "cshell"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

authors = [
    "Dominic Mayhew <dominic.mayhew@txpipe.io>",
    "Santiago Carmuega <santiago@txpipe.io>"
    ]
description = "A Cardano wallet CLI built for developers."
readme = "README.md"
repository = "https://github.com/txpipe/cshell"
license = "Apache-2.0"

keywords = ["cardano", "blockchain", "wallet", "cardano"]
categories = ["command-line-utilities", "blockchain", "cardano", "wallet"]

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.29", features = ["derive", "env"] }
comfy-table = "7.1.1"
hex = { version = "0.4.3", features = ["serde"] }
inquire = "0.7.4"
miette = { version = "7.2.0", features = ["fancy"] }
pallas = { version = "0.32.0", features = ["unstable", "pallas-wallet"] }
pallas-wallet = "0.32.0"
prost = "0.13.5"
rand = {version = "0.6.4"}
rand_core = {version = "0.6.4"}
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
slug = "0.1.5"
tokio = { version = "1.43.0", features = ["full"] }
tokio-stream = "0.1.17"
toml = "0.8.20"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = { version = "2.5.0", features = ["serde"] }
utxorpc = { git = "https://github.com/utxorpc/rust-sdk" }
