[package]
name = "cshell"
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0"

authors = ["Dominic Mayhew <dominic.mayhew@txpipe.io>"]
description = "A Cardano wallet CLI built for developers."
readme = "README.md"
repository = "https://github.com/txpipe/cshell"
license = "Apache-2.0"

keywords = ["cardano", "blockchain", "wallet", "cardano"]
categories = ["command-line-utilities", "blockchain", "cardano", "wallet"]

[dependencies]
