[package]
name = "cshell"
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0"

authors = [
    "Dominic Mayhew <dominic.mayhew@txpipe.io>",
    "Santiago Carmuega <santiago@txpipe.io>"
    ]
description = "A Cardano wallet CLI built for developers."
readme = "README.md"
repository = "https://github.com/txpipe/cshell"
license = "Apache-2.0"

keywords = ["cardano", "blockchain", "wallet", "cardano"]
categories = ["command-line-utilities", "blockchain", "cardano", "wallet"]

[dependencies]
chrono = { version = "0.4.37", features = ["serde"] }
clap = { version = "4.5.4", features = ["derive", "env"] }
comfy-table = "7.1.1"
directories = { version = "5.0.1" }
hex = "0.4.3"
indicatif = "0.17.8"
inquire = "0.7.4"
miette = { version = "7.2.0", features = ["fancy"] }
pallas = { version = "0.25.0", features = ["unstable"] }
prost = "0.12.4"
rand = "0.8.5"
sea-orm = { version = "0.12.15", features = ["sqlx-sqlite", "runtime-async-std-native-tls", "macros"] }
sea-orm-migration = { version = "0.12.15", features = ["runtime-tokio-rustls", "sqlx-sqlite"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
slug = "0.1.5"
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
toml = "0.8.12"
tracing = "0.1.40"
tracing-indicatif = "0.3.6"
tracing-subscriber = "0.3.18"
url = { version = "2.5.0", features = ["serde"] }
utxorpc = "0.1.0"
