[package]
name = "cshell"
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0"

authors = ["Dominic Mayhew <dominic.mayhew@txpipe.io>"]
description = "A Cardano wallet CLI built for developers."
readme = "README.md"
repository = "https://github.com/txpipe/cshell"
license = "Apache-2.0"

keywords = ["cardano", "blockchain", "wallet", "cardano"]
categories = ["command-line-utilities", "blockchain", "cardano", "wallet"]

[dependencies]
clap = { version = "4.5.4", features = ["derive", "env"] }
directories = { version = "5.0.1" }
miette = { version = "7.2.0", features = ["fancy"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-indicatif = "0.3.6"
tracing-subscriber = "0.3.18"
